---
title: "Minnesota sites"
---


<style>
   body {margin-left: 0px;}
  .main-container {max-width: 1350px;}
  tr:nth-child(even){background-color: #e9e9e9;
  tr:nth-child(odd){background-color: #FFF;}
</style>

<script type="text/JavaScript">
  setTimeout(function() { window.location=window.location;}, 350000);
</script>


<hr> 

```{r kable_MN, message=F, echo=F, results='asis', warning=F}
library(knitr)

options(warn = -1)

data <- filter(aqi_rank, AqsID %in% c(mn_sites$AqsID, border_sites, extra_sites))

data <- data[ , c(1:4,8,5,7,9)]

data$Agency <- gsub("Minnesota Pollution Control Agency", "MPCA", data$Agency)

names(data)[c(2,7,8)] <- c("Sampling Hour", "Concentration", "1-hr AQI")

kable(data[ , c(4,5,1:2,6:8)], 'html', align = 'lllllcc')

if(nrow(data) < 1) {
  cat(" *The table is currently empty. ")
} 
```
<br>

<div class = "gray">
## Missing parameters for Minnesota
```{r miss_MN, message=F, echo=F, results='asis', warning=F}

missing_mn <- mn_sites[!mn_sites$Site_Param %in% paste(aqi$AqsID, aqi$Parameter, sep="_"), ]

kable(arrange(missing_mn[ , c(1,4,3,2)], `Site Name`), 'html', align = 'llll')

if(length(missing_mn) < 1) {
  cat(" *There were no missing sites or parameters.")
} 
```
</div>

